### ISSUE TITLE
License metadata field currently not validated to be URL

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#109]
Not a big issue; just for future reference. The documentation is asking for a URL, but right now, adding 

`CC-BY 4` as a license string is not flagged up during validation.

**Comment by beckyjackson** [comment]
`build/metadata.tsv` is not currently validated. I'll add this to the validation script.

**Comment by beckyjackson** [comment]
We should use JSON schema to validate the metadata
