### ISSUE TITLE
Pre-populate mapping field with best suggestion >0.97 

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#112]
As requested by @mcourtot and @GiselleMarie (and discussed with @jamesaoverton) we should pre-populate the dropdown menu with the Gecko categories in Google with the best guess _if it is higher than 0.97_ (this makes sure we only add certain mappings). So if the best guess is lower (or equal) than 0.97, keep the mapping field blank.

**Comment by jamesaoverton** [comment]
I had an idea to make this a little fancier. I don't think we need to do it, but maybe someone else will think it's important:

When the system does this automatic assignment, we could also highlight these assignments ("INFO", blue) with a note that they're automatic. Subsequent passes of the validator would remove these highlights -- the submitter only needs to see them once.

**Comment by matentzn** [comment]
Sounds great to me!
