### ISSUE TITLE
We currently allow mapping data items to multiple GECKO terms

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#115]
This issue is just to be explicit about it. Sometimes, a data dictionary term fits in more than one GECKO category, thats why we allow this. @mcourtot this issue is assigned to you and if you agree with allowing this, then you can immediately close it again.

**Comment by mcourtot** [comment]
That does sound ok. Do you have a particular example you can share?

**Comment by matentzn** [comment]
There are a few, for example this one:


https://registry.ihccglobal.app/ontologies/ge/terms?iri=https%3A%2F%2Fpurl.ihccglobal.org%2FGE_0000300

You can see, it is mapped both to "physiological" and "laboratory" measurement!

**Comment by mcourtot** [comment]
hm - there is no definition or any kind of metadata, so hard to know whether that's correct or not. Should there at least be a definition if not a proper label or more attributes?

**Comment by matentzn** [comment]
@beckyjackson - I assume there are no definitions for most of these data dictionary terms?

**Comment by beckyjackson** [comment]
Correct. GE has some, but not all their terms have definitions

**Comment by mcourtot** [comment]
so how was that term mapped? from "invest2_09" to "physiological" and "laboratory" measurement seems quite a leap :)

**Comment by beckyjackson** [comment]
@mcourtot GE has many of the same terms with different numbers, for example:
* invest2_01
* invest2_02
* invest3_03
... and so on

Usually the "01" term, while it doesn't have a definition, has a label. In this case, the label is "A&E Investigation: 2 character". Since there was no context to this, I assumed it had to be either a physiological measure (e.g., taking heart rate) or a laboratory measure (e.g., urine test) as part of an investigation in the emergency department.

**Comment by mcourtot** [comment]
I see thanks @beckyjackson 

Would it be possible in such cases to add an editor note to the term explaining this inference? Maybe for future cohorts. 

Actually that makes me think of mapping provenance - eg http://purl.obolibrary.org/obo/ECO_0000305 - and maybe something we should think about capturing at some point (again, nice to have and think about, not critically needed right now)

**Comment by beckyjackson** [comment]
I believe this is resolved. I opened a new issue in regards to mapping provenance.
