### ISSUE TITLE
Make sure data dictionary version iris resolve

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#145]
1. Explore options
   - [ ] Using github releases `koges\v2020`
   - [ ] Using python script that links to the commit at the data of the date.

2. Implement suitable workflow for maintaining data dictionary releases
   - [ ] if github release solution: make it easy to "release a single data dictionary" (Droid?)
   - [ ] if python script: Work with @jamesaoverton to fiddle python script into nginx server.

**Comment by mcourtot** [comment]
I was just going to create a ticket for https://purl.ihccglobal.org/VZ_0000017 for individual terms as well - is this part of the same ticket?

**Comment by matentzn** [comment]
This is a new ticket - should be much easier to solve! -> at least if the redirect is simply a redirect to OLS :)

**Comment by jamesaoverton** [comment]
Sorry, I was sure that I had already configured term PURLs, but I didn't. I'll take care of this ASAP!

**Comment by jamesaoverton** [comment]
I fixed the term IRIs. I'll fix the ontology IRIs now. @matentzn is working on the ontology version IRIs, which are a bit trickier.

**Comment by jamesaoverton** [comment]
The main ontology IRIs should be working now, e.g. https://purl.ihccglobal.org/vz.owl

**Comment by jamesaoverton** [comment]
Resolved by #148
