### ISSUE TITLE
Hide suggested categories under a minimum confidence level

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/data-harmonization#149]
Right now, the "suggested categories" part of the mapping template is filled with "survey administration" for almost every term with a confidence of 0.1 - 0.3. These are almost always incorrect suggestions, and I think having it there does more harm than good for the user.

I would rather have us display less suggested categories with a higher level of confidence. I think a good cutoff for our automated pipeline is 0.4, but it would be nice to have this configurable so we can change it in the future.

CC @matentzn

**Comment by beckyjackson** [comment]
@matentzn it looks like "survey administration" also gets assigned if it can't figure out what the category might be? For example, in one of the cohorts I'm working on now, their labels are not very informative, and all the terms were suggested "survey administration" with a confidence of 0.9.

**Comment by matentzn** [comment]
That's I guess the downside of Machine Learning! It must be that this category is very often associated, and therefore serves as a kind of fall through.. Maybe we need to manually avoid mapping to "survey administration"? Alternatively, we switch off the ML based pipeline (or if you are interested: have at it! Maybe you can find ways to tweak it) and rely only on previous mappings like zooma does. But 0.9 is very high.. Did you search the zooma tsv files for the exact match? maybe it was previously asserted?

Do you feel comfortable with actually working with the NLP code? Maybe you can improve it! It was not really tested well before it was deployed..

**Comment by jamesaoverton** [comment]
I think it'll be faster for @beckyjackson to make these changes herself, as needed.

**Comment by matentzn** [comment]
Maybe this is a good place to add a restriction, but I have not thought too long about it:
https://github.com/IHCC-cohorts/data-harmonization/blob/e911b9a857019f69b6bf42f6c454eb27f9e7ad85/src/mapping-suggest/merge-mapping-suggestions.py#L58
