### ISSUE TITLE
Case sensitivity in the browser facets

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/data-harmonization#160]
During the dry run demo yesterday @christinayung showed the DAC browser and there were 2 blood facets: "blood" and "Blood"
Can you please check if this is in the JSON?

**Comment by jamesaoverton** [comment]
@beckyjackson replied here saying she sees only "Blood": https://github.com/IHCC-cohorts/data-harmonization/issues/137#issuecomment-764707837

I just double-checked and I agree with her: I only see "Blood" in the JSON.

**Comment by mcourtot** [comment]
sorry missed the issue from @rosibaj 

@rosibaj @beckyjackson can we identify where the duplicate is coming from?

**Comment by rosibaj** [comment]
@mcourtot @beckyjackson @jamesaoverton - the data in the dry-run yesterday was not from the updated data set that Becky sent yesterday.   In the most recent DAC data, I did not see this duplicate happening either.  Jon is deploying that data now, so i was going to do a final check in that view.  

I will confirm here when that is complete, but i think that this particular note is non-issue right now. 

@jamesaoverton re: your suggestion, the best option is usually sentence case (as IHCC is using), excepting specialized terms like `MRI` or `DNA`

**Comment by beckyjackson** [comment]
I believe this is resolved. @rosibaj can you confirm?

**Comment by rosibaj** [comment]
@beckyjackson confirmig resolved and closing.
