### ISSUE TITLE
Download links do not work

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/data-harmonization#166]
in the little listing on the right next to each dictionary at https://registry.ihccglobal.app/ontologies

eg https://registry.ihccglobal.app/ontologies/gecko/download, or https://registry.ihccglobal.app/ontologies/koges/download

**Comment by jamesaoverton** [comment]
I had hoped that #148 would resolve this, but it does not. So I'm pretty sure that this is an OLS problem.

**Comment by matentzn** [comment]
The diagnosis was a bit of a treasure hunt, but the solution beautifully simple. Thank you @udp for the support!

**Comment by matentzn** [comment]
Tested just now and works:
https://registry.ihccglobal.app/ontologies

**Comment by mcourtot** [comment]
Yay, thanks all!
