### ISSUE TITLE
20210521 - Data Review from OICR 

### ISSUE THREAD

**Issue by rosibaj** [IHCC-cohorts/data-harmonization#172]
- [ ] This PI's name included title, unlike all other leads.  This is inconsistent.
 https://github.com/IHCC-cohorts/data-harmonization/blob/7c0478c64c7b4b308188fc4556ec0928db8ac073/data/cohort-data.json#L833

**Comment by rosibaj** [comment]
@beckyjackson @jamesaoverton @mcourtot I reviewed that data updates and just found this one inconsistency - this might look weird on the UI against all the other investigators names.  Is this something we can fix?

**Comment by beckyjackson** [comment]
Sure, I can just remove the "Prof."
