### ISSUE TITLE
Replace "robot tree" with Gizmos?

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/data-harmonization#176]
We are currently using a never-released ROBOT command to generate the tree browsers for the workflow (`robot tree`). This code hasn't been updated and I don't think there are any plans to update it.

@jamesaoverton would it be beneficial to replace `robot tree` with `gizmos.tree`? We would just need to also create the SQLite databases, which we aren't doing for anything else at this time. That said, the ROBOT trees are working fine (for now).

**Comment by jamesaoverton** [comment]
Yes, please go ahead and make that change.
