### ISSUE TITLE
Validation problem when email does not have *.gmail

### ISSUE THREAD

**Issue by cgarcia5** [IHCC-cohorts/data-harmonization#179]
I'm doing a cohort upload to test the DROID system.
When I tried to upload the file (attached) in "Step 1- Upload Cohort Data", I got a "400 Bar Request" error (picture attached) after submission.
It seemd there could be a problem with email address not having *.gmail.
Thanks
![Error image](https://user-images.githubusercontent.com/86718682/124459112-b7dc7780-dd85-11eb-8751-ce66feca32ba.png)
[ihcc-data-dictionary-registration-template_CARLES.xlsx](https://github.com/IHCC-cohorts/data-harmonization/files/6763601/ihcc-data-dictionary-registration-template_CARLES.xlsx)

**Comment by jamesaoverton** [comment]
Yes, that's a bug in our email validation. Thank you for reporting it. We'll get it fixed quickly.
