### ISSUE TITLE
Update maelstrom.owl

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#182]
We have a [`data_dictionaries/maelstrom.owl`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/data_dictionaries/maelstrom.owl) file but it seems to be missing metadata, and it is not yet included in OLS:

1. [`metadata/maelstrom.ttl`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/metadata/maelstrom.ttl) file does not seem to be merged into the OWL file
2. [`metadata/maelstrom.ttl`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/metadata/maelstrom.ttl) might need to be updated. @mcourtot?
3. [`data/ols-config.yaml`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/data/ols-config.yaml) needs to include Maelstrom
4. the OLS server will need to be updated

@mcourtot Can you please check [`metadata/maelstrom.ttl`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/metadata/maelstrom.ttl)? Then I'll ask @beckyjackson to update 1,2,3 and @theisuru to complete 4.

**Comment by mcourtot** [comment]
the metadata file should be updated to refer to CC-BY 4.0, as per https://github.com/maelstrom-research/maelstrom-taxonomies

**Comment by mcourtot** [comment]
https://github.com/IHCC-cohorts/data-harmonization/blob/master/data_dictionaries/maelstrom.owl doesn't show numerical IDs for Maelstrom terms eg   <owl:Class rdf:about="https://purl.ihccglobal.org/MAELSTROM_Act_daily_living">

Are we not assigning IDs?

**Comment by jamesaoverton** [comment]
@beckyjackson will update `maelstrom.ttl` to use CC-BY-4 and the `maelstrom.owl` to use the numeric IDs assigned in the template.

@mcourtot Are there any other changes you want made to [`maelstrom.ttl`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/metadata/maelstrom.ttl)?

**Comment by mcourtot** [comment]
I think it's all good - what do you think?

**Comment by jamesaoverton** [comment]
I think it's ok.

@beckyjackson please proceed with plan outlined above, and when that's done we'll coordinate with @theisuru to get the OLS and OXO instances updated.

**Comment by jamesaoverton** [comment]
@theisuru we've completed steps 1-3 above. Can you please update the OLS/OXO server?

**Comment by jamesaoverton** [comment]
@beckyjackson Please update our https://github.com/IHCC-cohorts/data-harmonization/blob/master/data/maelstrom.yml with the latest version here https://github.com/maelstrom-research/maelstrom-taxonomies/blob/master/AreaOfInformation.yml and rebuild the `maelstrom.owl`. Please make sure that our conversion script is using as much of the YAML content as possible. Note that about a dozen Maelstrom classes were dropped, a dozen were added, and some were moved in the YAML. I think we're safe to reassign the numeric IDs.

**Comment by jamesaoverton** [comment]
@theisuru Please update OLS/OXO so that Maelstrom will be included.

**Comment by theisuru** [comment]
@jamesaoverton I updated the instances. Could you please check if it is there as expected.

**Comment by jamesaoverton** [comment]
Thanks @theisuru!

I can see Maelstrom ontology here: https://registry.ihccglobal.app/ontologies/maelstrom

I can see Maelstrom mappings here: https://mapping.ihccglobal.app/datasources/MAELSTROM

So I'll close this issue.

The only strange thing is that I no longer see the pretty graph view of mapping connections on our OXO home page: <https://mapping.ihccglobal.app/>. I just see a blank space, while on the main OXO I see a fancy circular diagram: <https://www.ebi.ac.uk/spot/oxo/>. Can you confirm @theisuru?

**Comment by theisuru** [comment]
I can also see that circular graph is not drawn in our OxO instance. Following API call returns an empty response. I will check why. 
`https://mapping.ihccglobal.app/api/mappings/summary`
