### ISSUE TITLE
Identify and collect cohort administration variables

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/data-harmonization#32]
In our last catch up we discussed the possibility of collecting some cohort level administrative metadata for each cohort. This could be stored in a separate ttl/owl file for each cohort. The OICR [desired JSON output](https://github.com/jamesaoverton/IHCC/issues/29) includes some of that information.

TODO:
- [ ] @rosibaj to make a flat list of attributes required per cohort
- [ ] Giselle to fetch metadata where possible from cohort
- [ ] @jamesaoverton @beckyjackson to provide a template to be filled for pipeline processing

**Comment by rosibaj** [comment]
@mcourtot The first attributes i listed were based off of the IHCC member cohort list int he website (https://ihcc.g2mc.org/membercohorts/).  The flat list of variables based on that would be:

- cohort_name
- countries
- current enrollment
- target enrollment
- pi_lead
- website

There may be more variables of interest, perhaps about data sharing potential/rules. I am limited as I do not know what other metadata the IHCC program is actually collecting about its member cohorts.  Is that list available anywhere?

**Comment by mcourtot** [comment]
Based on the IHCC and DPUk websites I have this list:
- Cohort Name	
- Short description
- Project website
- PI - Lead	
- Contact
- Participating countries	
- Current Enrolment number
- Target Enrolment number	
- Enrolment Period	
- Age at recruitment
- Sex
- Genomic Data	
- Environmental Data	
- Biospecimens	
- Phenotypic /Clinical Data	
- Data Sharing Potential
- Data access process (direct access via portal, please enquire, access via <website>)

I am not quite sure how data sharing potential is evaluated.

@jamesaoverton, @beckyjackson: if you can give us a list of all cohorts you are considering/working with we will send you back the corresponding metadata that we can find. We can then create individual metadata files for each. If you send a template we'll use that, otherwise we'll just put everything in a CSV.

**Comment by mcourtot** [comment]
Can we please add licence?

**Comment by mcourtot** [comment]
@GiselleMarie - can you please help with collecting this data? @jamesaoverton and @beckyjackson have already extracted what they could from the IHCC website table (see https://github.com/jamesaoverton/IHCC/issues/29#issuecomment-611994128), but if you could keep an eye out on what may be missing in the file they produce that'd be great - I suspect it will need a little bit of manual TLC.

**Comment by jamesaoverton** [comment]
@mcourtot A spreadsheet with these columns would be great.

We have KoGES mapped and are working on GCS, then we'll work our way down the list.

**Comment by mcourtot** [comment]
Do you have the version you extracted from the IHCC available as seed? Then we don't need to reextract these...

**Comment by jamesaoverton** [comment]
We have this file https://github.com/jamesaoverton/IHCC/blob/master/data/member_cohorts.csv

**Comment by mcourtot** [comment]
@jamesaoverton @beckyjackson would you be able to use the file sent by Eric at https://docs.google.com/spreadsheets/d/1lHDCzOOdUZy4d0NFaO36p0jV_S85tec5kUa8limfOqw/edit#gid=1233474139 directly, or do we need to format it differently or...?

**Comment by beckyjackson** [comment]
Sure @mcourtot !

Is it possible to make that sheet public so that I can download it automatically in our `Makefile`?

**Comment by mcourtot** [comment]
Let's check with Eric on Friday - can you run it without this to start with?

**Comment by beckyjackson** [comment]
Yeah, no problem! Thanks.

**Comment by jamesaoverton** [comment]
Sorry, I'm confused.

@mcourtot The Google Sheet has basically the same columns as our `member_cohorts.csv`. It has more cohorts, but they aren't marked as public. I don't think we can should publish information about cohorts unless they're marked "Information available on open website" = "Yes". So I don't think this Google Sheet gives us new information that we can share.

Can you please confirm?

**Comment by mcourtot** [comment]
I *think* Eric said he would send infomration we could use publicly; but let's check with him.
