### ISSUE TITLE
Create IHCC github organisation and decide licensing

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/data-harmonization#33]
As discussed on our call April 3rd, Thomas and Philip will look into those. 

Thomas said "Agreed we should do this so we have a place to put all the work products from the atlas. I'm happy with CC-BY for data, and Apache 2.0 for code (will check with Christina Y that she is happy with this). I will email the IHCC SC to let them know that we are setting this up."

**Comment by mcourtot** [comment]
https://github.com/IHCC-cohorts created by @tk2

@jamesaoverton and @beckyjackson can we move stuff over?

**Comment by jamesaoverton** [comment]
Yes, it looks like everything is ready. One last question: What do you want me to name this repo?

The current repository name is "IHCC", but I think that's more general than you want going forward. Ideas:

- IHCC-ontologies
- IHCC-data-harmonization

**Comment by mcourtot** [comment]
I'd go for 3. unless you think there is a benefit repeating the IHCC as in 2. ?

**Comment by jamesaoverton** [comment]
I agree that 3 is the best. I'll do that now. We can still change our mind later.

**Comment by jamesaoverton** [comment]
Ok. Here we are in our new home.

**Comment by mcourtot** [comment]
We should have a virtual house warming party.
