### ISSUE TITLE
Decide on an IRI policy

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#4]
Our ontology terms need IRIs. This is both a technical and a social issue:

1. technical: It's good for IRIs to live behind some sort of PURL redirect system, so if the source documents move the PURL system can be updated, and the IRIs will still resolve.

2. social: Names matter to people, and an IRI is one kind of name.

Until this is figured out, I guess we can point to this GitHub repo <https://github.com/jamesaoverton/IHCC/#> or maybe <http://ihcc.g2mc.org/#>.

Once the base IRIs are figured out, we also need a policy for term IDs. We could follow OBO-style numeric IDs, or we could use strings based on term labels.

**Comment by mcourtot** [comment]
I'd prefer to stick with numerical IDs for terms.

Not sure about the base IRI... can we have something that would be along the lines of purl.ihcc.org/cineca, purl.ihcc.org/xxxx (where xx is a short name for the data dictionary source)?

Not sure how easy or not it would get to have a CNAME set for those purls though.

I don't think we'll set up a redirect right now, but it is good to be prepared indeed. What would you suggest?

**Comment by jamesaoverton** [comment]
<http://ihcc.org> belongs to Indian Hills Community Church 😄 

Maybe something like <https://ihcc.g2mc.org/ontologies/> would be easier than setting up a new subdomain. It doesn't have to say "purl". Then term IDs like <https://ihcc.g2mc.org/ontologies/CINECA_0001234>.

**Comment by jamesaoverton** [comment]
EBI seems to use http://identifiers.org

**Comment by jamesaoverton** [comment]
It would also be good to get a proper URL for the OLS/OXO server.

**Comment by mcourtot** [comment]
Let's plan to use ihccglobal.org/dictionaryname/ for the IRIs, but for GECKO for which we'd like an OBO Purl.

**Comment by jamesaoverton** [comment]
Ok, but can you give me an example? What IRI do you want for this term:

http://193.62.55.169:8080/ontologies/koges/terms?iri=http%3A%2F%2Fexample.com%2FKoGES_0000067

**Comment by jamesaoverton** [comment]
This should all be working now: https://purl.ihccglobal.org/KoGES_0000060
