### ISSUE TITLE
Set up OLS and OxO instances

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#45]
I have the required credentials. There's a bit of a learning curve, but I'll work on this.

**Comment by jamesaoverton** [comment]
These should be branded for IHCC: logo in the corner from https://ihcc.g2mc.org, g2mc logo funding from bottom, link to main IHCC website somewhere.

See this OLS issue for branding: https://github.com/EBISPOT/OLS/issues/332

**Comment by jamesaoverton** [comment]
@mcourtot I now have an OLS instance running on my laptop, loading our seven ontologies.

It's based off the `master` branch of OLS, and looks like <https://www.ebi.ac.uk/ols/index>. I also tried the `ebi-rebranded-merged2` branch, as referred to in https://github.com/EBISPOT/OLS/issues/332. The basic rebranding stuff seems to work but lots of fundamental things are broken, like browsing ontologies. Either those things are just broken on that branch, or the documentation hasn't been updated for some crucial component. I don't think it's a good use of my time to debug that, when the `master` branch is working fine.

Tomorrow I'll hack at my local version of `master` branch to do some basic rebranding. I'll send you a screenshot that we can discuss. If you have specific requests for the screenshot, please let me know.

Then I'll work on getting this running on Embassy.

**Comment by jamesaoverton** [comment]
Update: I got the branding working using @matentzn's OLS branch <https://github.com/EBISPOT/OLS/tree/make-test-ui>, and I sent @mcourtot a screenshot. Now I'm working on deploying this to Embassy.

**Comment by jamesaoverton** [comment]
I now have a basic OLS instance running on the Web: <http://193.62.55.169:8080>

**Comment by jamesaoverton** [comment]
I have an instance of OxO running, but it only has one mapping in it right now: http://193.62.55.169:8081/search

Two questions for @mcourtot:

1. OxO does not have any branding options that I can see. What do you want me to do about that?
2. I thought that OxO did the actually mapping work, but it doesn't, it just displays the mappings. Do you know what tool was used to generate the mappings the appear on https://www.ebi.ac.uk/spot/oxo/ ?

**Comment by matentzn** [comment]
To be honest, no.. Its an OxO specific format, and we simply generate it on the fly with pandas (at least I do). Maybe @udp knows more, but I doubt it, since we have just resumed working on OxO again. You are working at a really bad time, OxO will undergo big changes soon, with SSSOM being the primary data standard for the mapping (which some will implement for ROBOT).. So for now, Just use Python. A hastily adjusted piece of code:

```
# Config is json blob like:
"""  
  alternateIris: null
  name: "SNOMED CT International"
  source: "ONTOLOGY"
  idorgNamespace: ""
  alternatePrefix: 
    - "SNOMEDCT"
    - "SNOMED"
  prefix: "SNOMEDCT"
  licence: "https://www.nlm.nih.gov/healthit/snomedct/snomed_licensing.html"
  orcid: null
  versionInfo: ""
  preferredPrefix: "SNOMEDCT"
"""
 # dfe contains two columns, fromCurie and toCurie

def prepare_ols_mapping(dfe,fromOID,config):
    df_mapping = dfe[['fromCurie','toCurie']]
    df_mapping['datasourcePrefix'] = fromOID
    df_mapping['datasource'] = json.dumps(config)
    df_mapping['sourceType'] = "ONTOLOGY"
    df_mapping['scope'] = "RELATED"
    df_mapping['date'] = date
    df_mapping.to_csv('snomed_mapping_oxo_old.csv')
```

**Comment by jamesaoverton** [comment]
Thanks @matentzn. I was trying to get at something different, but maybe I'm just confused.

I got the `oxo-loader` code working to find xrefs in our OLS instance (I think -- we don't actually have any yet). So I don't think I need that bit of Python.

I'm confused because I thought there was more to OxO than visualizing xref statements. I thought that there was some sort of synonym alignment or slightly fuzzy string matching being done.

Is there some other tool doing that work, that I'm missing?

**Comment by matentzn** [comment]
Ahh sorry I misunderstood you! OxO is just for serving existing mappings. The fact that it serves xrefs is just a secondary feature (to make all the OBO xrefs available into a centralised resource), and the main OLS use case is to ingest all kinds of mappings across ontologies and serve them up.. so no, it does not do any magic. There is a stack called PAXO which I thought did something based on label matching heuristics, but I can’t finde it now (maybe @LLTommy can shed some light). No magic mappings, sorry.  Now I am connecting also some of the dots of previous conversations.. you wanted something that automatically matched the data dictionaries you have indexed with obo and other ontologies.. sorry..

**Comment by jamesaoverton** [comment]
Ok., that's fine. We're doing manual mappings for IHCC, they'll be reliable, and OxO can visualize them.

A few years ago I tried to do some automated text-based (magic) mappings between NCIT and some OBOs. It didn't work very well. But I wanted to make sure I wasn't missing anything.

Thanks again @matentzn.

**Comment by jamesaoverton** [comment]
@mcourtot I still need an answer to this question: OxO does not have any branding options that I can see. What do you want me to do about that?

**Comment by udp** [comment]
@jamesaoverton  we will be adding similar customisation options to OxO as we have for OLS.  I will let you know when this has been implemented (likely this week)

**Comment by jamesaoverton** [comment]
The basics are working:

- https://registry.ihccglobal.app/index
- https://mapping.ihccglobal.app/search

I'll close this, and we can open new issues about specific problems.
