### ISSUE TITLE
Move GECKO to its own repository

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#50]
We're planning to submit GECKO to OBO. Hopefully other groups will use GECKO independently of the IHCC data harmonization work, so it makes sense to separate the ontology into its own repo. Here's a first draft of a plan:

1. create https://github.com/IHCC-cohorts/GECKO repo
2. create `src/ontology/` with `gecko.tsv` and `gecko.ttl`, better imports
3. create new, smaller `Makefile`
4. update this repo to pull `gecko.owl`

I think we should still use the same mappings Google Sheet as the source for `gecko.tsv`, at least for now.

**Comment by mcourtot** [comment]
Just to confirm this will all be based to the traditional structure with the edit files and the purl managed releases?

**Comment by jamesaoverton** [comment]
Yes, it will be an ontology repository similar to other OBO projects.

But OBO projects are increasingly using templates for their terms, and I want to do the same. For example, well over half of all OBI term are defined in templates; we're trying to convert existing branches to templates; and most new terms are added to templates.

https://github.com/obi-ontology/obi/tree/master/src/ontology/templates

**Comment by mcourtot** [comment]
just pinging this up - are you able to assess whether this is doable before end of May?

**Comment by jamesaoverton** [comment]
Yes, I will get it done. It shouldn't take long at all.

I planned to have this done already, but OXO is taking more time than I expected.

**Comment by jamesaoverton** [comment]
https://github.com/IHCC-cohorts
