### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#54]
We've been moving fast, but now it's time to write some high-level documentation. First draft:

- `Makefile`
  - a block comment at the top of each major section
  - make the OWL file more promiment
  - make the tree stuff less prominent

- `README.md`
  - overview
  - example workflow for a single cohort
  - what needs to be done to add a new cohort

**Comment by beckyjackson** [comment]
#53 has some changes to the `Makefile`. Is that ready to merge in? I don't want to run into any weird conflicts if I'm rearranging things.

**Comment by jamesaoverton** [comment]
Closed by #55
