### ISSUE TITLE
Provide instructions to Chip about IRI redirection

### ISSUE THREAD

**Issue by mcourtot** [IHCC-cohorts/data-harmonization#56]
As per https://github.com/IHCC-cohorts/data-harmonization/issues/4, we will use ihccglobal.org/dictionaryname for the cohorts. This means we need to redirect to our OLS instance from ihccglobal.org.

Chip said he could manage that, can we give him instructions?

**Comment by chipburris** [comment]
Do you want to be able to link to something inside of the Atlas? 
The IHCCGlobal.org Site is based on Wordpress.  I may be able to set a pattern, though, for some redirection.

One thing to keep in mind is I did reserve all of IHCCGlobal.app for the Atlas.

**Comment by chipburris** [comment]
I see some issues as well. I am trying to parse the format of the URL

http://193.62.55.169:8080/ontologies/koges/terms?iri=http://example.com/KoGES_0000112

**Comment by mcourtot** [comment]
We also need to decide on a URL for the registry - The EBI cloud team says redirection can be done on our side without their intervention.

**Comment by jamesaoverton** [comment]
Discussed with Chip and Melanie on a call today:

1. PURL for data dictionary terms: purl.ihccglobal.org CNAME 193.62.55.169
2. OLS instance: registry.ihccglobal.app CNAME 193.62.55.169
3. OXO instance: mapping.ihccglobal.app CNAME 193.62.55.169
4. IHCC Atlas browser (Overture) OICR team: ihccglobal.app A RECORD ??? (not yet public)

Example: <https://purl.ihccglobal.org/KoGES_0000001>  ==> <https://registry.ihccglobal.app/index?iri=https://purl.ihccglobal.org/KoGES_0000001>

**Comment by chipburris** [comment]
Done  I added  PURL/registry/mapping  to both ihccglobal.org and ihccglobal.app

**Comment by mcourtot** [comment]
Hi Chip - mapping.ihccglobal.app and registry.ihccglobal.app don't seem to resolve on my side. Can you help?

C02XG3Q1JHD3:~ courtot$ curl -v -L registry.ihccglobal.app
*   Trying 193.62.55.169...
* TCP_NODELAY set
* Connected to registry.ihccglobal.app (193.62.55.169) port 80 (#0)
> GET / HTTP/1.1
> Host: registry.ihccglobal.app
> User-Agent: curl/7.64.1
> Accept: */*
> 

Could it be the port which should be 8080 for OLS and 8081 for OxO? It seems to go to 80 by default.

**Comment by jamesaoverton** [comment]
That shows that what Chip did worked: The request is going to the right server.

I will revise the server configuration today.

**Comment by jamesaoverton** [comment]
These are all working now:

- https://purl.ihccglobal.org/KoGES_0000060
- https://registry.ihccglobal.app/index
- https://mapping.ihccglobal.app/

Thanks @chipburris!
