### ISSUE TITLE
Research tools for automated mapping

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#61]
We want to make the submission process for new data dictionaries as easy as possible for submitters, and take best advantage of the mappings already in the system. So we will try to automatically map the submitted terms to GECKO, and offer those automatic mappings as suggestions to the submitter.

The first thing is to look for existing open source tools that could do the core task, and that fit with the rest of the tools we're using: Linux, Python, Docker, possibly JVM.

[Zooma](https://github.com/EBISPOT/zooma) is one candidate. Unfortunately they are in the middle of a major refactoring, and we are on a tight deadline. We should keep Zooma integration in mind for the future.

Since we plan to integrate the automated mappings as one step in a workflow that's centred around a Google Sheet, we don't really need an interface, just the core matching algorithms.

**Comment by mcourtot** [comment]
@jamesaoverton @matentzn can you tell me a bit more what are the issues with zooma? we're using it in biosamples on a daily basis currently, and are planning on using for CINECA (which share goals with the IHCC browser) - if we pick something else I need to be able to explain why.

**Comment by matentzn** [comment]
No no, you can use Zooma, no problem - if you have the time! I was thinking more in terms of development + deployment _right now_. Zooma is at a crossroads between two different development stacks (version 2 and version 3 - we dont know which will win), which are not compatible (@udp is working on that), and is likely being revised significantly in the next months. So in 2 months from now, I would have said no problem! Now as far as I know, there is no way to deploy Zooma with docker, which means we would have to build a complete container set up zooma (@udp correct me if I am wrong), which costs a lot of time - that is potentially wasted if we bed on the wrong branch of the Zooma repo. Maybe @udp can give his perspective - how hard would it be (for me) to build a docker setup for zooma in the next 10 days?

**Comment by mcourtot** [comment]
Thanks for the feedback @matentzn. Agreed re docker - not sure it is really in scope for us to do that job (not saying we shouldn't if straightforward, but not the core mission of IHCC). From the functionality point ov view, it seems we'd like to do pretty much the same thing than BSD is doing - pass a list of terms and get matches - so just wondering why we can't use the current APIs for this.

**Comment by matentzn** [comment]
I dont know what BSD is, but you are right in terms of your description of the problem. @jamesaoverton and I will look into it next week and come up with a reasonable solution! :)

**Comment by matentzn** [comment]
This is done and good enough for now; using scikit learn. In future editions, consider NLTK and incorporating more fields.
