### ISSUE TITLE
Create JSON Schema for cohort-data.json

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#68]
As discussed on the IHCC call today, we're planning to maintain the status quo for communicating our results from data-harmonization to the Atlas browser: the [`data/cohort-data.json`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/data/cohort-data.json) file.

(We had been discussing a revised API, but the current approach is working so far. We can revisit that topic later, depending on funding.)

As we develop a self-serve workflow for cohorts to submit their dictionaries and mappings, we will continue to use the `master` branch of this GitHub repo as the "source of truth", and keep `data/cohort-data.json` up to date.

(NOTE: `data/cohort-data.json` only includes real mappings for the small number of cohorts we have mapped so far. [`full-cohort-data.json`](https://github.com/IHCC-cohorts/data-harmonization/blob/master/data/full-cohort-data.json) contains synthetic data for a larger number of cohorts.)

We do expect to be adding more mapping fields, which would be reflected in new facets in the Atlas browser. To help keep track of this, and ensure the structure of this file is always correct, we should develop a JSON Schema for `data/cohort-data.json`.

Does this all sound good to you @rosibaj ?

**Comment by beckyjackson** [comment]
The metadata schema should be separate from the mapped data schema

**Comment by mcourtot** [comment]
Tagging @theisuru - it'd be good to add the ontology checks from the elixir validator in particular to represent data sharing with DUO terms (or free-text, but suggesting DUO would be helpful)
