### ISSUE TITLE
Write a table validation script

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/data-harmonization#70]
We need a validation script for new cohort mappings, like the ones in the `templates/` directory.

This will be a small python script that looks at the contents based on the headers described in #62.

As far as workflow goes:
1. User fills out the Google Sheet
2. Run `cogs fetch && cogs pull` to update the local version (DROID button to kick this off, includes steps 2-5)
3. Run this script over the local version to output a standardized problems table
4. Run `cogs apply` with the standardized problems table
5. Run `cogs push` to update the remote version of the sheet
6. The user reviews the Google Sheet for any problems, fixes them, and repeats the process if necessary

This script should check for things like:
* Parent term exists as a label
* GECKO Category is an actual term from GECKO
* No duplicate labels

Perhaps warnings or info messages on missing GECKO categories? The user may not be able to map all their terms to existing categories, so it should be OK to leave them blank...

Would it make sense to also do automated ID assignment with this script, or is that handled elsewhere?

**Comment by jamesaoverton** [comment]
Good list. Yes, this script could handle automated ID assignment.
