### ISSUE TITLE
Implement and test automated mapping script

### ISSUE THREAD

**Issue by jamesaoverton** [IHCC-cohorts/data-harmonization#71]
@matentzn has Zooma working. Now we need to hook it up to our templates #62.

Right now we have a single "Suggested category" column in the templates. We need a script to fill this column from Zooma. Multiple suggested mappings are possible, so I would like to try an ordered, pipe-separated list of suggestions. I think it should look like this:

[Edited] `GOOD GECKO:0000069 alcohol | MEDIUM GECKO:0000067 lifestyle and behaviours`

The parsing steps would be:

1. split on pipe `|`
2. trim each part (remove leading and trailing whitespace)
3. split each part on whitespace into three values:
    - mapping confidence keyword (from Zooma) HIGH, GOOD, MEDIUM, LOW
    - CURIE
    - label

Once this is implemented, it should be tested on one (or more) of the mappings we've already done. `templates/koges.tsv` would be a good first test. For the test, we need to make sure that Zooma doesn't include the KOGES mappings.

**Comment by matentzn** [comment]
This has been completed.
