### ISSUE TITLE
Running a quick test locally without affecting public google sheets

### ISSUE THREAD

**Issue by theisuru** [IHCC-cohorts/data-harmonization#78]
Hi, I wanted to quickly test the tool without really doing any global changes to project related files. As to the documentation I have to modify [ROBOT template Google spreadsheet](https://docs.google.com/spreadsheets/d/1FwYYlJPzFAAItZyaKY2YnP01yQw6BkARq3CPifQSx1A) and [master GECKO mapping sheet](https://docs.google.com/spreadsheets/d/1IRAv5gKADr329kx2rJnJgtpYYqUhZcwLutKke8Q48j4). I am bit worried about making a mistake there, which might fail builds for all others. Can we use a local spreadsheet instead of this?

**Comment by jamesaoverton** [comment]
The README is a step behind the current work, sorry. You can edit your local copies of the TSV files in `templates/` and then run Make to update things.

**Comment by beckyjackson** [comment]
I think this can be closed since we've changed our workflow. Any opposition?
