### ISSUE TITLE
Fix versions for python dependencies?

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#79]
Just a reminder to self ([requirements](https://github.com/IHCC-cohorts/data-harmonization/blob/master/requirements.txt)). Also, we could consider to add the requirements.txt install as a make dependency? Not sure what the best practices are (I am saying this because I when I was running a first round of tutorial with @theisuru I realised that well, you need all the libs installed to run `make update` or `make all`.

**Comment by jamesaoverton** [comment]
We have been adding something [like this](https://github.com/knocean/practises/tree/master/python#setup) to our READMEs:

```
python3 -m venv _venv
source _venv/bin/activate
pip install -r requirements.txt
```

Then run Make. Is that what you mean?

**Comment by matentzn** [comment]
Yeah sure; maybe its fine to just document it rather than adding it to the makefile as a dependency. That was just a second thought. The main thing was fixing the versions!

**Comment by beckyjackson** [comment]
Is this still an issue? DROID is handling the dependencies now, so I don't think we need to worry about this?
