### ISSUE TITLE
Git error when running pipeline in ODK container

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#81]
When running the pipeline inside the ODK container, I get this error whenever I invoke make (any goal):

```
error: unknown option `show-current'
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] (-c | -C) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]
   or: git branch [<options>] [-r | -a] [--format]

Generic options
    -v .......... # some more stuff
```

The error does not cause the pipeline to fail, but I would like this to go away; seems that this is a relatively new git feature too. Can we perhaps get the branch somehow differently?

**Comment by matentzn** [comment]
@jamesaoverton

**Comment by jamesaoverton** [comment]
Becky is using `git branch --show-current` to guess the cohort ID when working on a new cohort. I want to be more explicit about it, so we'll end up doing it a different way.

**Comment by beckyjackson** [comment]
The cohort ID is now derived from the metadata sheet, so I believe this is resolved.
