### ISSUE TITLE
Get validation workflow running with DROID

### ISSUE THREAD

**Issue by beckyjackson** [IHCC-cohorts/data-harmonization#90]
The script should be included in the [Makefile](https://github.com/IHCC-cohorts/data-harmonization/blob/master/Makefile#L13). Running this script should fetch & pull the sheets from Google Sheets then run validation. The validation should be applied to the sheets.

@jamesaoverton can this be a bash script or would you rather have `validate.py` updated to do all the tasks?

**Comment by beckyjackson** [comment]
Following up, I figured this would just be a button in DROID that runs in the console, rather than a CGI script. Is that correct?

**Comment by matentzn** [comment]
Hey @beckyjackson I am currently finishing up step 3 in #77 

The interface looks something like: 

![image](https://user-images.githubusercontent.com/7070631/94431269-f573fa80-018c-11eb-97d0-e11e679958db.png)

I think it does not really matter how you implement the validation, but I run my part (3) it something like this: 

Makefile:
```
automated_mapping:
	make cogs_pull
	make mapping_suggest_cogs
	cogs push
```

**Comment by jamesaoverton** [comment]
@beckyjackson Yes, a task in the `Makefile` would be fine. Then this needs to link to the task:

https://github.com/IHCC-cohorts/data-harmonization/blob/master/Makefile#L13

Assume that COGS has already shared the Google Sheet with the submitter. COGS is working with files in `build/metadata.tsv` and `build/terminology.tsv`. Please add validation for the metadata sheet to your script.

**Comment by matentzn** [comment]
If you do metadata and terminology separately, that would be good - I already need metadata.tsv in step 3, so we could validate that one as part of the mapping process

**Comment by matentzn** [comment]
I think this is done now.
