### ISSUE TITLE
Data dictionaries: How to handle foreign ids?

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#92]
Currently, foreign ids are implicitly mapped by appending them to the data dictionary ids. For example, we have a term

`Admission source` in the Genomics England data dictionary, that has the official genomics england id `admisorc`. We assigned it, internally, the ID `GE:admisorc`.  The good thing about this is that it is 1) compact, i.e. does not take a lot of space, and 2) we dont need a seperate element. On the other hand, we 

- are making us dependent on external ID changes (what happens if an id gets changed? I mean it should not, but what if)
- Have slightly idiosyncratic ID schemes across our data dictionaries (some numeric, some external)
- We have to agree that external ID are generally URL encoded - which is a bit cumbersome in conjunction with CURIEs

The question is: should we introduce a new field for external ids?

**Comment by jamesaoverton** [comment]
@mcourtot What are your thoughts on this? Should we reuse the GE IDs in the PURLs that we're creating, or switch to numeric IDs like the other cohorts?

**Comment by matentzn** [comment]
After our last conversation, we should probably:

1. Make a new column that allows mapping external ids
2. Generate our own IDs according to the PREFIX:000000 recipe

**Comment by jamesaoverton** [comment]
Yes @matentzn, please implement that.

**Comment by jamesaoverton** [comment]
For example https://github.com/IHCC-cohorts/data-harmonization/blob/b807eac0ec61d6eb0bc26a2d61e8cb16010d8994/data_dictionaries/gcs.owl#L208
