### ISSUE TITLE
Duplicate ids in templates

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#95]
The following ids are non-unique:

```
GCS:DrugCurrentuse
VZ:UrineSampleCollected
VZ:UrineSampleNotCollectedReason
VZ:PipedTobaccoWeekly
VZ:UrineSampleCollectedId
```

**Comment by beckyjackson** [comment]
If we change everything to numeric IDs in #92 this will be resolved. Maybe that's a good argument to change everything to numeric IDs.

**Comment by matentzn** [comment]
Are these Ids non-unique in the source data dictionaries? That should be reported back to them! Even if we turn them into foreign id annotations, they should be unique, no?

**Comment by beckyjackson** [comment]
Since I copied everything from the source data dictionaries, I believe so. I will review these in the original data though!

**Comment by beckyjackson** [comment]
GCS:DrugCurrentuse
Appears on two different tabs in the data dictionary, but I suspect they are the same term. We should merge this one.

For Vukuzazi, it looks like they may be unintentional duplicates?
![image](https://user-images.githubusercontent.com/16750150/94570192-9241a100-023c-11eb-8049-b95ab6108fd8.png)

Perhaps it was meant to be something like `VZ:UrineSample1Collected` and `VZ:UrineSample2Collected`, like the swab samples shown above? This is something we should potentially report to them. Same with the other Vukuzazi duplicate IDs.

**Comment by matentzn** [comment]
Maybe thats for @mcourtot to think about - communicating this back to the Vukuzazi people?

**Comment by beckyjackson** [comment]
Since we are using numeric IDs now, I believe this is resolved.
