### ISSUE TITLE
Redirect to branch after upload process is done

### ISSUE THREAD

**Issue by matentzn** [IHCC-cohorts/data-harmonization#98]
Right now, after the data dictionary is updated, DROID is redirected to some page that allows viewing the spreadsheet, and a back button.

1. The back button currently does not work
2. Aside from that: I don't really see the need for this intermediate site;  why not just redirect to the branch page right after upload? The button to view the spreadsheet is there as well.

@jamesaoverton

**Comment by beckyjackson** [comment]
I fixed the back button in #94 but we might want to rework it anyway 🙂
